export const report_version_one = {
  overall_score: 6.8,
  weighted_score: 7.02,
  investment_readiness: "Series A Ready (with conditions)",
  confidence_level: "Medium",
  stage_assessment: "Early Growth Stage",
  risk_level: "Medium-High",
  core_metrics: [
    {
      name: "Problem-Solution Fit",
      category: "Foundation",
      score: 7.5,
      weight: 15,
      weighted_contribution: 1.125,
      percentile_rank: 75,
      benchmark_comparison: "Above Average",
      explanation:
        "The problem is clearly defined, but the solution's uniqueness and compelling value proposition need further elaboration.",
      evidence_strength: "Medium",
      evidence_found: ["problem description", "solution overview"],
      sub_metrics: {
        problem_clarity: 8,
        solution_relevance: 7,
        value_proposition: 7,
      },
    },
    {
      name: "Market Opportunity",
      category: "Market",
      score: 6,
      weight: 15,
      weighted_contribution: 0.9,
      percentile_rank: 60,
      benchmark_comparison: "Average",
      explanation:
        "Market size estimation is missing, hindering a proper assessment of the opportunity.  Growth trends are vaguely mentioned.",
      evidence_strength: "Weak",
      evidence_found: ["market trend mentions"],
      sub_metrics: {
        market_size: 4,
        market_growth: 7,
        timing: 6,
      },
    },
    {
      name: "Business Model Viability",
      category: "Business",
      score: 5,
      weight: 12,
      weighted_contribution: 0.6,
      percentile_rank: 50,
      benchmark_comparison: "Below Average",
      explanation:
        "Monetization strategy is unclear.  Pricing models and unit economics are not discussed, raising concerns about long-term viability.",
      evidence_strength: "Weak",
      evidence_found: [],
      sub_metrics: {
        revenue_clarity: 4,
        scalability: 6,
        sustainability: 5,
      },
    },
    {
      name: "Competitive Positioning",
      category: "Market",
      score: 4,
      weight: 12,
      weighted_contribution: 0.48,
      percentile_rank: 40,
      benchmark_comparison: "Below Average",
      explanation:
        "Competitive landscape is not analyzed.  No unique selling propositions are identified, making it difficult to assess differentiation.",
      evidence_strength: "Weak",
      evidence_found: [],
      sub_metrics: {
        differentiation: 3,
        competitive_moat: 4,
        positioning: 5,
      },
    },
    {
      name: "Product-Market Readiness",
      category: "Product",
      score: 6.5,
      weight: 12,
      weighted_contribution: 0.78,
      percentile_rank: 65,
      benchmark_comparison: "Average",
      explanation:
        "Product features are described, but evidence of product-market fit is limited.  Customer use cases are not detailed enough.",
      evidence_strength: "Medium",
      evidence_found: ["product features"],
      sub_metrics: {
        feature_completeness: 7,
        user_experience: 6,
        product_market_fit: 6,
      },
    },
    {
      name: "Traction & Validation",
      category: "Execution",
      score: 5.5,
      weight: 12,
      weighted_contribution: 0.66,
      percentile_rank: 55,
      benchmark_comparison: "Below Average",
      explanation:
        "No clear evidence of traction or validation is presented.  Metrics, testimonials, or case studies are absent.",
      evidence_strength: "Weak",
      evidence_found: [],
      sub_metrics: {
        customer_acquisition: 5,
        user_engagement: 5,
        revenue_growth: 6,
      },
    },
    {
      name: "Team Credibility",
      category: "Team",
      score: 7,
      weight: 8,
      weighted_contribution: 0.56,
      percentile_rank: 70,
      benchmark_comparison: "Above Average",
      explanation:
        "Team members' backgrounds and relevant experience are mentioned, building some confidence in their capabilities.",
      evidence_strength: "Medium",
      evidence_found: ["team bios"],
      sub_metrics: {
        founder_experience: 7,
        team_completeness: 7,
        advisory_strength: 7,
      },
    },
    {
      name: "Go-to-Market Strategy",
      category: "Execution",
      score: 4.5,
      weight: 6,
      weighted_contribution: 0.27,
      percentile_rank: 45,
      benchmark_comparison: "Below Average",
      explanation:
        "Target customer is vaguely defined.  Customer acquisition channels and market penetration strategies are missing.",
      evidence_strength: "Weak",
      evidence_found: [],
      sub_metrics: {
        customer_targeting: 5,
        acquisition_strategy: 4,
        distribution_channels: 4,
      },
    },
    {
      name: "Technology & Innovation",
      category: "Product",
      score: 3.5,
      weight: 4,
      weighted_contribution: 0.14,
      percentile_rank: 35,
      benchmark_comparison: "Below Average",
      explanation:
        "No evidence of proprietary technology or significant innovation is presented.  This is a major concern.",
      evidence_strength: "Weak",
      evidence_found: [],
      sub_metrics: {
        technical_innovation: 3,
        ip_protection: 2,
        technical_moat: 4,
      },
    },
    {
      name: "Presentation & Communication",
      category: "Presentation",
      score: 7.5,
      weight: 4,
      weighted_contribution: 0.3,
      percentile_rank: 75,
      benchmark_comparison: "Above Average",
      explanation:
        "Website is professionally designed and the messaging is clear, though it could be more compelling and data-driven.",
      evidence_strength: "Medium",
      evidence_found: ["website design", "messaging clarity"],
      sub_metrics: {
        messaging_clarity: 8,
        visual_presentation: 7,
        information_organization: 8,
      },
    },
  ],
  category_scores: {
    Foundation: 7.5,
    Market: 5,
    Business: 5,
    Product: 5,
    Execution: 5,
    Team: 7,
    Presentation: 7.5,
  },
  benchmark_data: {
    industry_average: 6,
    top_quartile_threshold: 7.5,
    investment_ready_threshold: 6.5,
    percentile_ranking: 65,
  },
  key_strengths: [
    "Experienced founding team",
    "Clear problem definition",
    "Professional website presentation",
  ],
  areas_for_improvement: [
    "Lack of market validation and traction",
    "Unclear business model and revenue generation strategy",
    "Absence of competitive analysis and differentiation",
  ],
  investment_recommendation: {
    summary:
      "The startup shows potential but requires significant improvements before a full investment commitment.  Further due diligence is crucial.",
    risk_level: "Medium-High",
    funding_stage_fit: "Series A (conditional)",
    investment_score: 6.8,
    potential_concerns: [
      "Lack of market validation",
      "Unclear revenue model",
      "Weak competitive positioning",
    ],
    positive_indicators: [
      "Experienced team",
      "Clear problem statement",
      "Good website presentation",
    ],
  },
  actionable_recommendations: [
    "Conduct thorough market research and provide detailed market sizing",
    "Develop a robust business model with clear pricing strategy and unit economics",
    "Perform competitive analysis and articulate unique selling propositions",
    "Demonstrate product-market fit with customer testimonials, case studies, and key metrics",
    "Define a clear go-to-market strategy with specific customer acquisition channels",
  ],
  missing_information: [
    "Market size data",
    "Financial projections",
    "Pricing model details",
    "Customer acquisition cost analysis",
    "Competitive landscape analysis",
    "Traction and growth metrics",
  ],
  analysis_metadata: {
    analyzed_at: "2025-09-23T06:52:16.223Z",
    model_used: "gemini-1.5-flash",
  },
};

export const report = {
  overall_score: 6.8,
  weighted_score: 6.82,
  investment_readiness: "Seed Stage",
  confidence_level: "High",
  stage_assessment: "Early Stage",
  risk_level: "Medium",
  analysis_date: "2024-01-15",
  industry_sector: "B2B SaaS",
  company_stage: "Pre-Seed",
  funding_estimate: "$500K - $1.5M",
  core_metrics: [
    {
      name: "Problem-Solution Fit",
      category: "Foundation",
      score: 7.5,
      weight: 15,
      weighted_contribution: 1.125,
      percentile_rank: 75,
      benchmark_comparison: "Above Average",
      explanation:
        "The website clearly identifies a problem and presents a solution. The value proposition is compelling and addresses a clear need.",
      evidence_strength: "Strong",
      evidence_found: [
        "problem statement",
        "solution overview",
        "value proposition",
      ],
      sub_metrics: {
        problem_clarity: 8,
        solution_relevance: 7,
        value_proposition: 7,
      },
      trend: "stable",
      confidence_level: 7.5,
    },
    {
      name: "Market Opportunity",
      category: "Market",
      score: 6,
      weight: 15,
      weighted_contribution: 0.9,
      percentile_rank: 60,
      benchmark_comparison: "Average",
      explanation:
        "The market opportunity is mentioned, but specific market sizing (TAM, SAM, SOM) is missing. Market trends are alluded to.",
      evidence_strength: "Medium",
      evidence_found: ["market overview", "industry trends"],
      sub_metrics: {
        market_size: 5,
        market_growth: 7,
        timing: 6,
      },
      trend: "stable",
      confidence_level: 6,
    },
    {
      name: "Business Model Viability",
      category: "Business",
      score: 5,
      weight: 12,
      weighted_contribution: 0.6,
      percentile_rank: 50,
      benchmark_comparison: "Below Average",
      explanation:
        "The website mentions a subscription-based model, but lacks detail on pricing, tiers, and unit economics. Scalability is implied.",
      evidence_strength: "Weak",
      evidence_found: ["pricing mention", "subscription model"],
      sub_metrics: {
        revenue_clarity: 5,
        scalability: 6,
        sustainability: 4,
      },
      trend: "stable",
      confidence_level: 5,
    },
    {
      name: "Competitive Positioning",
      category: "Market",
      score: 4.5,
      weight: 12,
      weighted_contribution: 0.54,
      percentile_rank: 45,
      benchmark_comparison: "Below Average",
      explanation:
        "The website mentions some differentiators but lacks a detailed competitive analysis. USP's are present but not strongly emphasized.",
      evidence_strength: "Weak",
      evidence_found: ["feature comparisons", "unique benefits"],
      sub_metrics: {
        differentiation: 4,
        competitive_moat: 3,
        positioning: 6,
      },
      trend: "stable",
      confidence_level: 4.5,
    },
    {
      name: "Product-Market Readiness",
      category: "Product",
      score: 7,
      weight: 12,
      weighted_contribution: 0.84,
      percentile_rank: 70,
      benchmark_comparison: "Above Average",
      explanation:
        "The product is well-described with clear features and benefits. Customer use cases are mentioned, indicating product-market fit.",
      evidence_strength: "Medium",
      evidence_found: [
        "feature list",
        "product descriptions",
        "customer benefits",
      ],
      sub_metrics: {
        feature_completeness: 7,
        user_experience: 7,
        product_market_fit: 7,
      },
      trend: "stable",
      confidence_level: 7,
    },
    {
      name: "Traction & Validation",
      category: "Execution",
      score: 5.5,
      weight: 12,
      weighted_contribution: 0.66,
      percentile_rank: 55,
      benchmark_comparison: "Average",
      explanation:
        "Some early traction is indicated, but specific metrics (e.g., user growth, revenue) are missing. Customer testimonials are present.",
      evidence_strength: "Weak",
      evidence_found: ["customer testimonials", "early adopters"],
      sub_metrics: {
        customer_acquisition: 5,
        user_engagement: 6,
        revenue_growth: 5,
      },
      trend: "improving",
      confidence_level: 5.5,
    },
    {
      name: "Team Credibility",
      category: "Team",
      score: 6,
      weight: 8,
      weighted_contribution: 0.48,
      percentile_rank: 60,
      benchmark_comparison: "Average",
      explanation:
        "Founder backgrounds are mentioned, but more detail on relevant experience and expertise is needed. Team qualifications are aligned.",
      evidence_strength: "Medium",
      evidence_found: ["founder bios", "team page"],
      sub_metrics: {
        founder_experience: 6,
        team_completeness: 5,
        advisory_strength: 6,
      },
      trend: "stable",
      confidence_level: 6,
    },
    {
      name: "Go-to-Market Strategy",
      category: "Execution",
      score: 4,
      weight: 6,
      weighted_contribution: 0.24,
      percentile_rank: 40,
      benchmark_comparison: "Below Average",
      explanation:
        "The target customer is defined, but the customer acquisition strategy lacks detail. Distribution channels are not clearly identified.",
      evidence_strength: "Weak",
      evidence_found: ["target audience description"],
      sub_metrics: {
        customer_targeting: 5,
        acquisition_strategy: 3,
        distribution_channels: 4,
      },
      trend: "stable",
      confidence_level: 4,
    },
    {
      name: "Technology & Innovation",
      category: "Product",
      score: 4,
      weight: 4,
      weighted_contribution: 0.16,
      percentile_rank: 40,
      benchmark_comparison: "Below Average",
      explanation:
        "Limited evidence of proprietary technology or significant innovation. Technical capabilities are mentioned but not deeply explored.",
      evidence_strength: "Weak",
      evidence_found: ["technology mentions"],
      sub_metrics: {
        technical_innovation: 4,
        ip_protection: 3,
        technical_moat: 5,
      },
      trend: "stable",
      confidence_level: 4,
    },
    {
      name: "Presentation & Communication",
      category: "Presentation",
      score: 8,
      weight: 4,
      weighted_contribution: 0.32,
      percentile_rank: 80,
      benchmark_comparison: "Above Average",
      explanation:
        "The website is well-designed and professional. Messaging is clear and concise, and the overall presentation is compelling.",
      evidence_strength: "Strong",
      evidence_found: ["website design", "clear messaging", "user experience"],
      sub_metrics: {
        messaging_clarity: 8,
        visual_presentation: 8,
        information_organization: 8,
      },
      trend: "stable",
      confidence_level: 8,
    },
  ],
  category_scores: {
    Foundation: 7.5,
    Market: 5.25,
    Business: 5,
    Product: 6,
    Execution: 5,
    Team: 6,
    Presentation: 8,
  },
  benchmark_data: {
    industry_average: 6,
    top_quartile_threshold: 7.2,
    investment_ready_threshold: 6.5,
    percentile_ranking: 68,
    peer_companies: [
      {
        name: "Competitor A",
        score: 6.8,
        stage: "Seed",
        funding: 1.2,
      },
      {
        name: "Competitor B",
        score: 6.5,
        stage: "Seed",
        funding: 0.8,
      },
      {
        name: "Market Leader",
        score: 8.5,
        stage: "Series A",
        funding: 5,
      },
    ],
  },
  market_analysis: {
    tam_size: 5000000000,
    sam_size: 1000000000,
    som_size: 200000000,
    market_growth_rate: 20,
    market_maturity: "Emerging",
    competitive_intensity: "Medium",
    market_trends: [
      "Increasing demand for SaaS solutions",
      "Growing adoption of cloud-based services",
      "Focus on automation and efficiency",
    ],
    market_risks: [
      "Competition from established players",
      "Market saturation",
      "Economic downturn",
    ],
  },
  financial_projections: {
    current_revenue: 0,
    projected_revenue_y1: 0.5,
    projected_revenue_y2: 2,
    projected_revenue_y3: 6,
    projected_revenue_y5: 20,
    burn_rate: -0.2,
    runway_months: 18,
    next_funding_need: 1,
    valuation_estimate: 5,
    revenue_multiple: 10,
  },
  risk_assessment: {
    overall_risk_score: 5.8,
    risk_factors: [
      {
        category: "Market Risk",
        probability: 60,
        impact: 7,
        mitigation_score: 5,
        description: "Competition and market saturation",
      },
      {
        category: "Execution Risk",
        probability: 50,
        impact: 6,
        mitigation_score: 6,
        description: "Scaling the team and product development",
      },
      {
        category: "Financial Risk",
        probability: 45,
        impact: 8,
        mitigation_score: 4,
        description: "Funding and burn rate",
      },
      {
        category: "Technology Risk",
        probability: 30,
        impact: 5,
        mitigation_score: 7,
        description: "Technical scalability and IP protection",
      },
      {
        category: "Regulatory Risk",
        probability: 20,
        impact: 4,
        mitigation_score: 8,
        description: "Compliance and data privacy",
      },
    ],
  },
  funding_stage_analysis: {
    current_stage_fit: "Seed",
    readiness_score: 6.2,
    typical_funding_amount: "500K - 2M",
    time_to_next_stage: "12-18 months",
    stage_requirements: [
      "Product-market fit validation",
      "Early revenue generation",
      "Team expansion",
    ],
    stage_comparisons: [
      {
        stage: "Pre-Seed",
        typical_score: 4,
        funding_range: "50K - 500K",
      },
      {
        stage: "Seed",
        typical_score: 6,
        funding_range: "500K - 2M",
      },
      {
        stage: "Series A",
        typical_score: 7.5,
        funding_range: "2M - 15M",
      },
      {
        stage: "Series B",
        typical_score: 8.5,
        funding_range: "15M - 50M",
      },
    ],
  },
  key_strengths: [
    "Clear problem-solution fit and compelling value proposition.",
    "Well-designed website with professional presentation and clear messaging.",
    "Strong product description with defined features and benefits.",
  ],
  areas_for_improvement: [
    "Lack of detailed competitive analysis and differentiation.",
    "Missing specific market sizing and go-to-market strategy details.",
    "Limited evidence of traction and early revenue generation.",
  ],
  investment_recommendation: {
    summary:
      "Promising startup with a strong foundation but needs to refine its market strategy and demonstrate early traction before a full investment.",
    recommendation: "Proceed with Due Diligence",
    risk_level: "Medium",
    funding_stage_fit: "Seed (conditional)",
    investment_score: 6.8,
    confidence_level: 70,
    timeline_to_investment: "6-9 months",
    due_diligence_priority: "Medium",
    potential_concerns: [
      "Lack of competitive differentiation.",
      "Limited market validation data.",
      "Unproven revenue model.",
    ],
    positive_indicators: [
      "Clear problem-solution fit.",
      "Strong product description.",
      "Experienced founding team.",
    ],
    next_steps: [
      "Deep dive into market analysis and competitive landscape.",
      "Review of early customer acquisition strategy.",
      "Detailed financial model review.",
    ],
  },
  actionable_recommendations: [
    {
      priority: "Critical",
      category: "Market Validation",
      action: "Conduct thorough market research and define TAM, SAM, and SOM.",
      timeline: "Next 60 days",
      impact: "High",
      effort: "Medium",
    },
    {
      priority: "High",
      category: "Competitive Analysis",
      action:
        "Develop a detailed competitive analysis and clearly articulate the unique selling propositions.",
      timeline: "Next 90 days",
      impact: "High",
      effort: "Medium",
    },
    {
      priority: "High",
      category: "Go-to-Market",
      action:
        "Define a clear customer acquisition strategy and distribution channels.",
      timeline: "Next 60 days",
      impact: "High",
      effort: "Medium",
    },
    {
      priority: "Medium",
      category: "Traction",
      action: "Focus on generating early revenue and tracking key metrics.",
      timeline: "Next 90 days",
      impact: "Medium",
      effort: "High",
    },
    {
      priority: "Medium",
      category: "Business Model",
      action: "Refine the pricing strategy and unit economics.",
      timeline: "Next 45 days",
      impact: "Medium",
      effort: "Low",
    },
  ],
  missing_information: [
    "Detailed market sizing (TAM, SAM, SOM)",
    "Specific customer acquisition cost (CAC) and lifetime value (LTV) analysis",
    "Competitive landscape mapping and positioning matrix",
    "Detailed financial projections and unit economics",
    "Customer retention and churn metrics",
  ],
  analysis_metadata: {
    analyzed_at: "2024-01-15T10:30:00Z",
    model_used: "claude-3.5-sonnet",
    analysis_version: "v2.1",
    data_sources: ["website_content", "public_information"],
    confidence_score: 8,
    completeness_score: 7.5,
  },
};
