    const report = {
    overall_score: 6.8,
    weighted_score: 7.02,
    investment_readiness: "Series A Ready (with conditions)",
    confidence_level: "Medium",
    stage_assessment: "Early Growth Stage",
    risk_level: "Medium-High",
    core_metrics: [
        {
        name: "Problem-Solution Fit",
        category: "Foundation",
        score: 7.5,
        weight: 15,
        weighted_contribution: 1.125,
        percentile_rank: 75,
        benchmark_comparison: "Above Average",
        explanation:
            "The problem is clearly defined, but the solution's uniqueness and compelling value proposition need further elaboration.",
        evidence_strength: "Medium",
        evidence_found: ["problem description", "solution overview"],
        sub_metrics: {
            problem_clarity: 8,
            solution_relevance: 7,
            value_proposition: 7,
        },
        },
        {
        name: "Market Opportunity",
        category: "Market",
        score: 6,
        weight: 15,
        weighted_contribution: 0.9,
        percentile_rank: 60,
        benchmark_comparison: "Average",
        explanation:
            "Market size estimation is missing, hindering a proper assessment of the opportunity.  Growth trends are vaguely mentioned.",
        evidence_strength: "Weak",
        evidence_found: ["market trend mentions"],
        sub_metrics: {
            market_size: 4,
            market_growth: 7,
            timing: 6,
        },
        },
        {
        name: "Business Model Viability",
        category: "Business",
        score: 5,
        weight: 12,
        weighted_contribution: 0.6,
        percentile_rank: 50,
        benchmark_comparison: "Below Average",
        explanation:
            "Monetization strategy is unclear.  Pricing models and unit economics are not discussed, raising concerns about long-term viability.",
        evidence_strength: "Weak",
        evidence_found: [],
        sub_metrics: {
            revenue_clarity: 4,
            scalability: 6,
            sustainability: 5,
        },
        },
        {
        name: "Competitive Positioning",
        category: "Market",
        score: 4,
        weight: 12,
        weighted_contribution: 0.48,
        percentile_rank: 40,
        benchmark_comparison: "Below Average",
        explanation:
            "Competitive landscape is not analyzed.  No unique selling propositions are identified, making it difficult to assess differentiation.",
        evidence_strength: "Weak",
        evidence_found: [],
        sub_metrics: {
            differentiation: 3,
            competitive_moat: 4,
            positioning: 5,
        },
        },
        {
        name: "Product-Market Readiness",
        category: "Product",
        score: 6.5,
        weight: 12,
        weighted_contribution: 0.78,
        percentile_rank: 65,
        benchmark_comparison: "Average",
        explanation:
            "Product features are described, but evidence of product-market fit is limited.  Customer use cases are not detailed enough.",
        evidence_strength: "Medium",
        evidence_found: ["product features"],
        sub_metrics: {
            feature_completeness: 7,
            user_experience: 6,
            product_market_fit: 6,
        },
        },
        {
        name: "Traction & Validation",
        category: "Execution",
        score: 5.5,
        weight: 12,
        weighted_contribution: 0.66,
        percentile_rank: 55,
        benchmark_comparison: "Below Average",
        explanation:
            "No clear evidence of traction or validation is presented.  Metrics, testimonials, or case studies are absent.",
        evidence_strength: "Weak",
        evidence_found: [],
        sub_metrics: {
            customer_acquisition: 5,
            user_engagement: 5,
            revenue_growth: 6,
        },
        },
        {
        name: "Team Credibility",
        category: "Team",
        score: 7,
        weight: 8,
        weighted_contribution: 0.56,
        percentile_rank: 70,
        benchmark_comparison: "Above Average",
        explanation:
            "Team members' backgrounds and relevant experience are mentioned, building some confidence in their capabilities.",
        evidence_strength: "Medium",
        evidence_found: ["team bios"],
        sub_metrics: {
            founder_experience: 7,
            team_completeness: 7,
            advisory_strength: 7,
        },
        },
        {
        name: "Go-to-Market Strategy",
        category: "Execution",
        score: 4.5,
        weight: 6,
        weighted_contribution: 0.27,
        percentile_rank: 45,
        benchmark_comparison: "Below Average",
        explanation:
            "Target customer is vaguely defined.  Customer acquisition channels and market penetration strategies are missing.",
        evidence_strength: "Weak",
        evidence_found: [],
        sub_metrics: {
            customer_targeting: 5,
            acquisition_strategy: 4,
            distribution_channels: 4,
        },
        },
        {
        name: "Technology & Innovation",
        category: "Product",
        score: 3.5,
        weight: 4,
        weighted_contribution: 0.14,
        percentile_rank: 35,
        benchmark_comparison: "Below Average",
        explanation:
            "No evidence of proprietary technology or significant innovation is presented.  This is a major concern.",
        evidence_strength: "Weak",
        evidence_found: [],
        sub_metrics: {
            technical_innovation: 3,
            ip_protection: 2,
            technical_moat: 4,
        },
        },
        {
        name: "Presentation & Communication",
        category: "Presentation",
        score: 7.5,
        weight: 4,
        weighted_contribution: 0.3,
        percentile_rank: 75,
        benchmark_comparison: "Above Average",
        explanation:
            "Website is professionally designed and the messaging is clear, though it could be more compelling and data-driven.",
        evidence_strength: "Medium",
        evidence_found: ["website design", "messaging clarity"],
        sub_metrics: {
            messaging_clarity: 8,
            visual_presentation: 7,
            information_organization: 8,
        },
        },
    ],
    category_scores: {
        Foundation: 7.5,
        Market: 5,
        Business: 5,
        Product: 5,
        Execution: 5,
        Team: 7,
        Presentation: 7.5,
    },
    benchmark_data: {
        industry_average: 6,
        top_quartile_threshold: 7.5,
        investment_ready_threshold: 6.5,
        percentile_ranking: 65,
    },
    key_strengths: [
        "Experienced founding team",
        "Clear problem definition",
        "Professional website presentation",
    ],
    areas_for_improvement: [
        "Lack of market validation and traction",
        "Unclear business model and revenue generation strategy",
        "Absence of competitive analysis and differentiation",
    ],
    investment_recommendation: {
        summary:
        "The startup shows potential but requires significant improvements before a full investment commitment.  Further due diligence is crucial.",
        risk_level: "Medium-High",
        funding_stage_fit: "Series A (conditional)",
        investment_score: 6.8,
        potential_concerns: [
        "Lack of market validation",
        "Unclear revenue model",
        "Weak competitive positioning",
        ],
        positive_indicators: [
        "Experienced team",
        "Clear problem statement",
        "Good website presentation",
        ],
    },
    actionable_recommendations: [
        "Conduct thorough market research and provide detailed market sizing",
        "Develop a robust business model with clear pricing strategy and unit economics",
        "Perform competitive analysis and articulate unique selling propositions",
        "Demonstrate product-market fit with customer testimonials, case studies, and key metrics",
        "Define a clear go-to-market strategy with specific customer acquisition channels",
    ],
    missing_information: [
        "Market size data",
        "Financial projections",
        "Pricing model details",
        "Customer acquisition cost analysis",
        "Competitive landscape analysis",
        "Traction and growth metrics",
    ],
    analysis_metadata: {
        analyzed_at: "2025-09-23T06:52:16.223Z",
        model_used: "gemini-1.5-flash",
    },
    };
